name: 'Mongo import files'
description: 'Import json files into an existing MongoDB database'
inputs:
  path: 
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
    default: '.'
  uri: 
    description: 'MongoDB connection string'
    required: true
    default: ''
  database: 
    description: 'Database name'
    required: true
    default: ''
  collection: 
    description: 'Collection name'
    required: true
    default: ''
  keep-collection: 
    description: 'Do not clear the collection before importing new files.'
    required: false
    default: false
  if-no-files-found:
    description: >
      The desired behavior if no files are found using the provided path.
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: 'warn'
runs:
  using: 'node16'
  main: 'dist/index.js'